import crypto from "crypto";
import serviceFacade from "../../../services/service.facade";

//tabla
// CREATE TABLE API_KEYS (
//     "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     "NOMBRE" NVARCHAR(100) NOT NULL,
//     "KEY_HASH" NVARCHAR(64) NOT NULL UNIQUE,
//     "ACTIVO" BOOLEAN DEFAULT TRUE NOT NULL,
//     "CREADO_EN" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
//     "REVOCADO_EN" TIMESTAMP NULL,
//     "ULTIMO_USO" TIMESTAMP NULL
// );

export class ApikeyBusiness {

    generateApiKey = ():string =>{
        return crypto.randomBytes(32).toString("hex").toUpperCase();
    }

    getHashApiKey = ():string => {
        const apiKey = this.generateApiKey()
        return crypto
            .createHash("sha256")
            .update(apiKey)
            .digest("hex");
    }

    getApikey = async () => {
        try {
            const apikey = await serviceFacade.hanaDb.query("SELECT * FROM API_KEYS");
            console.info("✅ Apikey obtenida exitosamente");
            return apikey;
        } catch (error) {
            throw error;
        }
    };

    //find by key_hash 
    findApikey = async (body: { key_hash: string }) => {
        try {
            const apikey = await serviceFacade.hanaDb.query("SELECT * FROM API_KEYS WHERE key_hash = ?", [body.key_hash]);
            console.info("✅ Apikey obtenida exitosamente");
            return apikey;
        } catch (error) {
            throw error;
        }
    };

    //create
    createApikey = async (body: { nombre: string, key_hash: string }) => {
        try {
            const resp = await serviceFacade.hanaDb.execute("INSERT INTO API_KEYS (nombre, key_hash) VALUES (?, ?)", [body.nombre, body.key_hash]);
            console.info("✅ Apikey creada exitosamente");
            return resp;
        } catch (error) {
            throw error;
        }
    };
    //update
    updateApikey = async (body: { nombre: string, key_hash: string, activo: boolean }) => {
        try {
            const resp = await serviceFacade.hanaDb.execute("UPDATE API_KEYS SET nombre = ?, key_hash = ?, activo = ? WHERE nombre = ?", [body.nombre, body.key_hash, body.activo, body.nombre]);
            console.info("✅ Apikey actualizada exitosamente");
            return resp;
        } catch (error) {
            throw error;
        }
    };
    //delete
    deleteApikey = async (body: { nombre: string }) => {
        try {
            const resp = await serviceFacade.hanaDb.execute("DELETE FROM API_KEYS WHERE nombre = ?", [body.nombre]);
            console.info("✅ Apikey eliminada exitosamente");
            return resp;
        } catch (error) {
            throw error;
        }
    };
}